/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: VelveteenDreamTest.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @VelveteenDreamTest: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("characters", () => this.@characters, val => this.@characters = val);
			VarDef("leftCharacter", () => this.@leftCharacter, val => this.@leftCharacter = val);
			VarDef("rightCharacter", () => this.@rightCharacter, val => this.@rightCharacter = val);
		}

		public StoryVar @characters;
		public StoryVar @leftCharacter;
		public StoryVar @rightCharacter;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@VelveteenDreamTest()
	{
		this.StartPassage = "SceneName_Initializer";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: SceneName_Initializer

	void passage1_Init()
	{
		this.Passages[@"SceneName_Initializer"] = new StoryPassage(@"SceneName_Initializer", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		Vars.characters  = macros1.a("Tadeo","Christian","Nicole","Lea","Sean");
		yield return lineBreak();
		Vars.leftCharacter  = "Tadeo";
		yield return lineBreak();
		Vars.rightCharacter  = "Lea";
		yield return lineBreak();
		yield return link("Continue", "SceneName01A", null);
		yield return text("Enter Scene");
		yield break;
	}


	// .............
	// #2: SceneName01A

	void passage2_Init()
	{
		this.Passages[@"SceneName01A"] = new StoryPassage(@"SceneName01A", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		Vars.rightCharacter  = "Christian";
		yield return lineBreak();
		yield return text("Tadeo:\"Hey, Christian, I fucking love you.\"");
		yield break;
	}


}