/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Cafe_Ava_Day1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Cafe_Ava_Day1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Jade", () => this.@Jade, val => this.@Jade = val);
			VarDef("Ava", () => this.@Ava, val => this.@Ava = val);
			VarDef("characters", () => this.@characters, val => this.@characters = val);
			VarDef("avaMeter", () => this.@avaMeter, val => this.@avaMeter = val);
			VarDef("claudioMeter", () => this.@claudioMeter, val => this.@claudioMeter = val);
			VarDef("lutherMeter", () => this.@lutherMeter, val => this.@lutherMeter = val);
			VarDef("leftCharacter", () => this.@leftCharacter, val => this.@leftCharacter = val);
			VarDef("rightCharacter", () => this.@rightCharacter, val => this.@rightCharacter = val);
			VarDef("jadeHappy", () => this.@jadeHappy, val => this.@jadeHappy = val);
			VarDef("jadeSad", () => this.@jadeSad, val => this.@jadeSad = val);
			VarDef("jadeAngry", () => this.@jadeAngry, val => this.@jadeAngry = val);
			VarDef("jadeNeutral", () => this.@jadeNeutral, val => this.@jadeNeutral = val);
			VarDef("avaHappy", () => this.@avaHappy, val => this.@avaHappy = val);
			VarDef("avaSad", () => this.@avaSad, val => this.@avaSad = val);
			VarDef("avaAngry", () => this.@avaAngry, val => this.@avaAngry = val);
			VarDef("avaNeutral", () => this.@avaNeutral, val => this.@avaNeutral = val);
			VarDef("backToGym", () => this.@backToGym, val => this.@backToGym = val);
			VarDef("goingToJadeRoom", () => this.@goingToJadeRoom, val => this.@goingToJadeRoom = val);
		}

		public StoryVar @Jade;
		public StoryVar @Ava;
		public StoryVar @characters;
		public StoryVar @avaMeter;
		public StoryVar @claudioMeter;
		public StoryVar @lutherMeter;
		public StoryVar @leftCharacter;
		public StoryVar @rightCharacter;
		public StoryVar @jadeHappy;
		public StoryVar @jadeSad;
		public StoryVar @jadeAngry;
		public StoryVar @jadeNeutral;
		public StoryVar @avaHappy;
		public StoryVar @avaSad;
		public StoryVar @avaAngry;
		public StoryVar @avaNeutral;
		public StoryVar @backToGym;
		public StoryVar @goingToJadeRoom;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Cafe_Ava_Day1()
	{
		this.StartPassage = "Cafe-Ava-Day1-Init";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Cafe-Ava-Day1-Init

	void passage1_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-Init"] = new StoryPassage(@"Cafe-Ava-Day1-Init", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		Vars.Jade  = "Jade";
		yield return lineBreak();
		Vars.Ava  = "Ava";
		yield return lineBreak();
		yield return lineBreak();
		Vars.characters  = macros1.a(Vars.Jade, Vars.Ava);
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaMeter  = 10;
		yield return lineBreak();
		Vars.claudioMeter  = 0;
		yield return lineBreak();
		Vars.lutherMeter  = 0;
		yield return lineBreak();
		yield return lineBreak();
		Vars.leftCharacter  = Vars.Jade;
		yield return lineBreak();
		Vars.rightCharacter  = Vars.Ava;
		yield return lineBreak();
		yield return lineBreak();
		Vars.jadeHappy  = false;
		yield return lineBreak();
		Vars.jadeSad  = false;
		yield return lineBreak();
		Vars.jadeAngry  = false;
		yield return lineBreak();
		Vars.jadeNeutral  = true;
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaHappy  = false;
		yield return lineBreak();
		Vars.avaSad  = false;
		yield return lineBreak();
		Vars.avaAngry  = false;
		yield return lineBreak();
		Vars.avaNeutral  = true;
		yield return lineBreak();
		yield return lineBreak();
		Vars.backToGym  = false;
		yield return lineBreak();
		Vars.goingToJadeRoom  = false;
		yield return lineBreak();
		yield return lineBreak();
		yield return abort(goToPassage: "Cafe-Ava-Day1-1");
		yield break;
	}


	// .............
	// #2: Cafe-Ava-Day1-1

	void passage2_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-1"] = new StoryPassage(@"Cafe-Ava-Day1-1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Ava: So, Jade, tell me about your character in the ring. What are you like?");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-2", null);
		yield break;
	}


	// .............
	// #3: Cafe-Ava-Day1-2

	void passage3_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-2"] = new StoryPassage(@"Cafe-Ava-Day1-2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Jade: Well...");
		yield return lineBreak();
		yield return link("<br>I'm more of a rebel type. ", "Cafe-Ava-Day1-3-A", null);
		yield return lineBreak();
		yield return link("<br>I'm like the calm, silent, strong type.", "Cafe-Ava-Day1-3-B", null);
		yield return lineBreak();
		yield return link("<br>I think I'm cute, but a badass at the same time.", "Cafe-Ava-Day1-3-C", null);
		yield break;
	}


	// .............
	// #4: Cafe-Ava-Day1-3-A

	void passage4_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-3-A"] = new StoryPassage(@"Cafe-Ava-Day1-3-A", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		Vars.claudioMeter  = Vars.claudioMeter + 5;
		yield return text("Ava: Oh, that’s kind of like Claudio. I think you two would get along!");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-4", null);
		yield break;
	}


	// .............
	// #5: Cafe-Ava-Day1-3-B

	void passage5_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-3-B"] = new StoryPassage(@"Cafe-Ava-Day1-3-B", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		Vars.lutherMeter  = Vars.lutherMeter + 5;
		yield return text("Ava: Oh wow, that’s kind of like the Division 1 champ right now, Luther. Looks like you got being the D-1 champ coming in your future if you’re taking after him!");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #6: Cafe-Ava-Day1-3-C

	void passage6_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-3-C"] = new StoryPassage(@"Cafe-Ava-Day1-3-C", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaHappy  = true;
		yield return text("Ava: Hehe, that’s kind of like me!");
		Vars.avaMeter  = Vars.avaMeter +5;
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: Cafe-Ava-Day1-4

	void passage7_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-4"] = new StoryPassage(@"Cafe-Ava-Day1-4", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		Vars.jadeHappy  = true;
		Vars.jadeNeutral  = false;
		yield return text("Jade: Oh, uh, nice!");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-5", null);
		yield break;
	}


	// .............
	// #8: Cafe-Ava-Day1-5

	void passage8_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-5"] = new StoryPassage(@"Cafe-Ava-Day1-5", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("A nervous young man approaches Ava at the table.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-6", null);
		yield break;
	}


	// .............
	// #9: Cafe-Ava-Day1-6

	void passage9_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-6"] = new StoryPassage(@"Cafe-Ava-Day1-6", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		Vars.avaHappy  = false;
		Vars.avaNeutral  = true;
		yield return text("Young Man: Ms… Ms—Ms. Sweet Spike! C-C-Can I get an a-autograph??? My hat! P-Please autograph my hat!");
		Vars.jadeHappy  = false;
		Vars.jadeNeutral  = true;
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-7", null);
		yield break;
	}


	// .............
	// #10: Cafe-Ava-Day1-7

	void passage10_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-7"] = new StoryPassage(@"Cafe-Ava-Day1-7", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaAngry  = true;
		yield return text("Ava: Eh? You think I would soil my name by putting it on some random loser’s hat?");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-8", null);
		yield break;
	}


	// .............
	// #11: Cafe-Ava-Day1-8

	void passage11_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-8"] = new StoryPassage(@"Cafe-Ava-Day1-8", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Ava: Tch, tell you what, if I see you at the show, then maybe I’ll think about looking in your direction. ");
		using (Group("strong", true)) {
			yield return text("Maybe");
		}
		yield return text(".");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-9", null);
		yield break;
	}


	// .............
	// #12: Cafe-Ava-Day1-9

	void passage12_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-9"] = new StoryPassage(@"Cafe-Ava-Day1-9", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Ava: For now, get the fuck out of my sight.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-10", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #13: Cafe-Ava-Day1-10

	void passage13_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-10"] = new StoryPassage(@"Cafe-Ava-Day1-10", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Young Man: Th-THANK YOU SWEET SPIKE! I LOVE YOU!");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-11", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #14: Cafe-Ava-Day1-11

	void passage14_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-11"] = new StoryPassage(@"Cafe-Ava-Day1-11", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("The Young Man leaves the cafe. He looks quite excited.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-12", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: Cafe-Ava-Day1-12

	void passage15_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-12"] = new StoryPassage(@"Cafe-Ava-Day1-12", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		Vars.jadeNeutral  = false;
		Vars.jadeSad  = true;
		yield return text("Jade: Woah, that was pretty harsh. I thought you were… you know, sweet? You turned into a bad guy?");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-13", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #16: Cafe-Ava-Day1-13

	void passage16_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-13"] = new StoryPassage(@"Cafe-Ava-Day1-13", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		Vars.avaAngry  = false;
		Vars.avaNeutral  = true;
		yield return text("Ava: Yeah, I was sweeter before the injury, but AOW wants me to be heel for my return to D-1.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-14", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #17: Cafe-Ava-Day1-14

	void passage17_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-14"] = new StoryPassage(@"Cafe-Ava-Day1-14", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Ava: Makes sense you didn’t know I was heel because you couldn't watch D-3. But yeah, I’m a heel now.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-15", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #18: Cafe-Ava-Day1-15

	void passage18_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-15"] = new StoryPassage(@"Cafe-Ava-Day1-15", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		Vars.jadeSad  = false;
		Vars.jadeNeutral  = true;
		yield return lineBreak();
		yield return link("<br>Heel? Like, the bad guy, right? ", "Cafe-Ava-Day1-16-A", null);
		yield return lineBreak();
		yield return link("<br>So, the bad guy is called a heel around here?", "Cafe-Ava-Day1-16-B", null);
		yield return lineBreak();
		yield return link("<br>You’re supposed to boo the heel, right? The bad guy.", "Cafe-Ava-Day1-16-C", null);
		yield break;
	}


	// .............
	// #19: Cafe-Ava-Day1-16-A

	void passage19_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-16-A"] = new StoryPassage(@"Cafe-Ava-Day1-16-A", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("Jade: Heel? Like, the bad guy, right? Sorry, still getting used to the terminology.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #20: Cafe-Ava-Day1-16-B

	void passage20_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-16-B"] = new StoryPassage(@"Cafe-Ava-Day1-16-B", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Jade: So, the bad guy is called a heel around here? Sorry, still getting used to the terminology.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #21: Cafe-Ava-Day1-16-C

	void passage21_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-16-C"] = new StoryPassage(@"Cafe-Ava-Day1-16-C", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Jade: You’re supposed to boo the heel, right? The bad guy. Sorry, still getting used to the terminology.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #22: Cafe-Ava-Day1-17

	void passage22_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-17"] = new StoryPassage(@"Cafe-Ava-Day1-17", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("Jade: Back from where I'm from, Cascadia, we never really used the terms.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-18", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #23: Cafe-Ava-Day1-18

	void passage23_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-18"] = new StoryPassage(@"Cafe-Ava-Day1-18", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Jade: We just kind of went with the fans on who they wanted to cheer or boo that night.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-19", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #24: Cafe-Ava-Day1-19

	void passage24_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-19"] = new StoryPassage(@"Cafe-Ava-Day1-19", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("Jade: Is AOW that strict about that kind of thing? Always being your character and everything?");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-20", null);
		yield break;
	}


	// .............
	// #25: Cafe-Ava-Day1-20

	void passage25_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-20"] = new StoryPassage(@"Cafe-Ava-Day1-20", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("Ava: Well, not so much in D-1, but in the lower divisions? Absolutely. Especially in D-3.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-21", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #26: Cafe-Ava-Day1-21

	void passage26_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-21"] = new StoryPassage(@"Cafe-Ava-Day1-21", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("Ava: People really want to believe that whatever they’re watching is real. Even if it’s painfully obvious that it’s not.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-22", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #27: Cafe-Ava-Day1-22

	void passage27_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-22"] = new StoryPassage(@"Cafe-Ava-Day1-22", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("Ava: So, outside of the ring, you gotta make sure to act the same.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-23", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #28: Cafe-Ava-Day1-23

	void passage28_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-23"] = new StoryPassage(@"Cafe-Ava-Day1-23", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("Ava: You know, kayfabe, presenting everything that happening in-ring like it’s real? Have to keep up the act in and outside of the ring.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-24", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #29: Cafe-Ava-Day1-24

	void passage29_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-24"] = new StoryPassage(@"Cafe-Ava-Day1-24", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("Jade: I guess I never thought much of it. There wasn’t much room to believe what was happening was real where I was.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-25", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #30: Cafe-Ava-Day1-25

	void passage30_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-25"] = new StoryPassage(@"Cafe-Ava-Day1-25", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Jade: A bunch of the other wrestlers were less than half organic.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-26", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #31: Cafe-Ava-Day1-26

	void passage31_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-26"] = new StoryPassage(@"Cafe-Ava-Day1-26", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaHappy  = true;
		yield return text("Ava: That does remind me, you have to tell me what made you want to stay full organic some time. ");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-27", null);
		yield break;
	}


	// .............
	// #32: Cafe-Ava-Day1-27

	void passage32_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-27"] = new StoryPassage(@"Cafe-Ava-Day1-27", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("Jade: Maybe... It's a long story.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-28", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #33: Cafe-Ava-Day1-28

	void passage33_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-28"] = new StoryPassage(@"Cafe-Ava-Day1-28", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("Ava: All good! We can trade stories whenever you want. ");
		Vars.avaMeter  = Vars.avaMeter + 5;
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-29", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #34: Cafe-Ava-Day1-29

	void passage34_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-29"] = new StoryPassage(@"Cafe-Ava-Day1-29", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		Vars.avaHappy  = false;
		Vars.avaNeutral  = true;
		yield return text("Ava: Anyway, you have a match coming up Monday right? We should definitely talk about it for a bit.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-30", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #35: Cafe-Ava-Day1-30

	void passage35_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-30"] = new StoryPassage(@"Cafe-Ava-Day1-30", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("Jade: Oh, okay, sure!");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-31", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #36: Cafe-Ava-Day1-31

	void passage36_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-31"] = new StoryPassage(@"Cafe-Ava-Day1-31", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		yield return text("Ava: Silly, can’t be here, we need somewhere super secret! Like the AOW gym or something.");
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-32", null);
		yield break;
	}


	// .............
	// #37: Cafe-Ava-Day1-32

	void passage37_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-32"] = new StoryPassage(@"Cafe-Ava-Day1-32", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		yield return link("<br>Alright, let's head back to the gym then.", "Cafe-Ava-Day1-33-A", null);
		yield return lineBreak();
		yield return link("<br>Go back to the gym? I'd rather just relax at home...", "Cafe-Ava-Day1-33-B", null);
		yield break;
	}


	// .............
	// #38: Cafe-Ava-Day1-33-A

	void passage38_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-33-A"] = new StoryPassage(@"Cafe-Ava-Day1-33-A", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaHappy  = true;
		yield return text("Ava: Awesome! ");
		Vars.avaMeter  = Vars.avaMeter + 5;
		Vars.backToGym  = true;
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-End", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #39: Cafe-Ava-Day1-33-B

	void passage39_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-33-B"] = new StoryPassage(@"Cafe-Ava-Day1-33-B", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		Vars.goingToJadeRoom  = true;
		Vars.avaNeutral  = false;
		Vars.avaSad  = true;
		yield return text("Ava: Awww, that's okay. Rest up! I'll text you tonight then.");
		Vars.avaMeter  = Vars.avaMeter - 5;
		yield return lineBreak();
		yield return link("v", "Cafe-Ava-Day1-End", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #40: Cafe-Ava-Day1-End

	void passage40_Init()
	{
		this.Passages[@"Cafe-Ava-Day1-End"] = new StoryPassage(@"Cafe-Ava-Day1-End", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}