/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Gym_DayOne_Ava.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Gym_DayOne_Ava: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Jade", () => this.@Jade, val => this.@Jade = val);
			VarDef("Ava", () => this.@Ava, val => this.@Ava = val);
			VarDef("characters", () => this.@characters, val => this.@characters = val);
			VarDef("avaMeter", () => this.@avaMeter, val => this.@avaMeter = val);
			VarDef("leftCharacter", () => this.@leftCharacter, val => this.@leftCharacter = val);
			VarDef("rightCharacter", () => this.@rightCharacter, val => this.@rightCharacter = val);
			VarDef("jadeHappy", () => this.@jadeHappy, val => this.@jadeHappy = val);
			VarDef("jadeSad", () => this.@jadeSad, val => this.@jadeSad = val);
			VarDef("jadeAngry", () => this.@jadeAngry, val => this.@jadeAngry = val);
			VarDef("jadeNeutral", () => this.@jadeNeutral, val => this.@jadeNeutral = val);
			VarDef("avaHappy", () => this.@avaHappy, val => this.@avaHappy = val);
			VarDef("avaSad", () => this.@avaSad, val => this.@avaSad = val);
			VarDef("avaAngry", () => this.@avaAngry, val => this.@avaAngry = val);
			VarDef("avaNeutral", () => this.@avaNeutral, val => this.@avaNeutral = val);
		}

		public StoryVar @Jade;
		public StoryVar @Ava;
		public StoryVar @characters;
		public StoryVar @avaMeter;
		public StoryVar @leftCharacter;
		public StoryVar @rightCharacter;
		public StoryVar @jadeHappy;
		public StoryVar @jadeSad;
		public StoryVar @jadeAngry;
		public StoryVar @jadeNeutral;
		public StoryVar @avaHappy;
		public StoryVar @avaSad;
		public StoryVar @avaAngry;
		public StoryVar @avaNeutral;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Gym_DayOne_Ava()
	{
		this.StartPassage = "GymDayOne-Ava-Init";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: GymDayOne-Ava-Init

	void passage1_Init()
	{
		this.Passages[@"GymDayOne-Ava-Init"] = new StoryPassage(@"GymDayOne-Ava-Init", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("After a brief walk with Jade talking about her favorite moments watching All Out Wrestling, Jade and Ava end up back at the gym.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva01", null);
		yield return lineBreak();
		Vars.Jade  = "Jade";
		yield return lineBreak();
		Vars.Ava  = "Ava";
		yield return lineBreak();
		yield return lineBreak();
		Vars.characters  = macros1.a(Vars.Jade, Vars.Ava);
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaMeter  = 15;
		yield return lineBreak();
		yield return lineBreak();
		Vars.leftCharacter  = Vars.Jade;
		yield return lineBreak();
		Vars.rightCharacter  = Vars.Ava;
		yield return lineBreak();
		yield return lineBreak();
		Vars.jadeHappy  = false;
		yield return lineBreak();
		Vars.jadeSad  = false;
		yield return lineBreak();
		Vars.jadeAngry  = false;
		yield return lineBreak();
		Vars.jadeNeutral  = true;
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaHappy  = true;
		yield return lineBreak();
		Vars.avaSad  = false;
		yield return lineBreak();
		Vars.avaAngry  = false;
		yield return lineBreak();
		Vars.avaNeutral  = false;
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: GymDayOneAva01

	void passage2_Init()
	{
		this.Passages[@"GymDayOneAva01"] = new StoryPassage(@"GymDayOneAva01", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Ava: So anyway, I wanted to give you some contacts and all that. Do you know who you’re going to be working with?");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva02", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #3: GymDayOneAva02

	void passage3_Init()
	{
		this.Passages[@"GymDayOneAva02"] = new StoryPassage(@"GymDayOneAva02", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Jade: Can't say that I do.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva03", null);
		yield break;
	}


	// .............
	// #4: GymDayOneAva03

	void passage4_Init()
	{
		this.Passages[@"GymDayOneAva03"] = new StoryPassage(@"GymDayOneAva03", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		Vars.avaHappy  = false;
		Vars.avaNeutral  = true;
		yield return text("Ava: Really? When did you get hired?");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva04", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: GymDayOneAva04

	void passage5_Init()
	{
		this.Passages[@"GymDayOneAva04"] = new StoryPassage(@"GymDayOneAva04", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Jade: Tuesday.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva05", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #6: GymDayOneAva05

	void passage6_Init()
	{
		this.Passages[@"GymDayOneAva05"] = new StoryPassage(@"GymDayOneAva05", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Ava: Damn, really? Well, AOW is the most transparent organization out there, I guess.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva06", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: GymDayOneAva06

	void passage7_Init()
	{
		this.Passages[@"GymDayOneAva06"] = new StoryPassage(@"GymDayOneAva06", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Ava: Guess you should just show up Sunday and go for it.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva07", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #8: GymDayOneAva07

	void passage8_Init()
	{
		this.Passages[@"GymDayOneAva07"] = new StoryPassage(@"GymDayOneAva07", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Ava: Wait--");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva08", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #9: GymDayOneAva08

	void passage9_Init()
	{
		this.Passages[@"GymDayOneAva08"] = new StoryPassage(@"GymDayOneAva08", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Ava: What day did they tell you to start?");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva09", null);
		yield break;
	}


	// .............
	// #10: GymDayOneAva09

	void passage10_Init()
	{
		this.Passages[@"GymDayOneAva09"] = new StoryPassage(@"GymDayOneAva09", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Jade: Sunday.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva10", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11: GymDayOneAva10

	void passage11_Init()
	{
		this.Passages[@"GymDayOneAva10"] = new StoryPassage(@"GymDayOneAva10", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaHappy  = true;
		yield return text("Ava: Whew! Great!");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva11", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: GymDayOneAva11

	void passage12_Init()
	{
		this.Passages[@"GymDayOneAva11"] = new StoryPassage(@"GymDayOneAva11", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		Vars.avaHappy  = false;
		Vars.avaNeutral  = true;
		yield return text("Ava: Alright, so let me explain how AOW does things.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva12", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #13: GymDayOneAva12

	void passage13_Init()
	{
		this.Passages[@"GymDayOneAva12"] = new StoryPassage(@"GymDayOneAva12", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Ava: So, each Sunday you’re required to meet with the person you’ll be performing with. ");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva13", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #14: GymDayOneAva13

	void passage14_Init()
	{
		this.Passages[@"GymDayOneAva13"] = new StoryPassage(@"GymDayOneAva13", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Ava: It can be anywhere really, though a lot of people tend to do it at the gym or in their rooms at home.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva14", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: GymDayOneAva14

	void passage15_Init()
	{
		this.Passages[@"GymDayOneAva14"] = new StoryPassage(@"GymDayOneAva14", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return link("<br>What's the meeting for?", "GymDayOneAva15", null);
		yield return lineBreak();
		yield return link("<br>Wait, you guys meet up before matches?", "GymDayOneAva15", null);
		yield return lineBreak();
		yield return link("<br>A meeting?", "GymDayOneAva15", null);
		yield break;
	}


	// .............
	// #16: GymDayOneAva15

	void passage16_Init()
	{
		this.Passages[@"GymDayOneAva15"] = new StoryPassage(@"GymDayOneAva15", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Ava: Well, AOW likes to keep things tight so everyone’s in the loop. The meeting is for planning what you’ll be doing during the matches.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva16", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #17: GymDayOneAva16

	void passage17_Init()
	{
		this.Passages[@"GymDayOneAva16"] = new StoryPassage(@"GymDayOneAva16", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Ava: So, planning things out is standard protocol. Of course, there will be some people you work with who will ad lib on the spot, but generally they want to keep everything according to a plan.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #18: GymDayOneAva17

	void passage18_Init()
	{
		this.Passages[@"GymDayOneAva17"] = new StoryPassage(@"GymDayOneAva17", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		Vars.jadeNeutral  = false;
		Vars.jadeSad  = true;
		yield return text("Jade: Jade: Oh, planning…");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva18", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #19: GymDayOneAva18

	void passage19_Init()
	{
		this.Passages[@"GymDayOneAva18"] = new StoryPassage(@"GymDayOneAva18", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("Jade: What happens if I forget or something? I didn’t do too much planning beforehand.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva19", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #20: GymDayOneAva19

	void passage20_Init()
	{
		this.Passages[@"GymDayOneAva19"] = new StoryPassage(@"GymDayOneAva19", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Ava: Some people will get a little more upset than others, but they’ll try to help you out as best as they can.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva20", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #21: GymDayOneAva20

	void passage21_Init()
	{
		this.Passages[@"GymDayOneAva20"] = new StoryPassage(@"GymDayOneAva20", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Ava: Still, I wouldn’t take too many chances on some of the ones in the locker room regardless.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva21", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #22: GymDayOneAva21

	void passage22_Init()
	{
		this.Passages[@"GymDayOneAva21"] = new StoryPassage(@"GymDayOneAva21", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		Vars.avaNeutral  = false;
		Vars.avaHappy  = true;
		yield return text("Ava: I think you'll do great!");
		Vars.jadeSad  = false;
		Vars.avaNeutral  = true;
		yield return lineBreak();
		yield return link("v", "GymDayOneAva22", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #23: GymDayOneAva22

	void passage23_Init()
	{
		this.Passages[@"GymDayOneAva22"] = new StoryPassage(@"GymDayOneAva22", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Ava: Your first partner is this guy named Dante, he goes by D-800 in D3 AOW.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva23", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #24: GymDayOneAva23

	void passage24_Init()
	{
		this.Passages[@"GymDayOneAva23"] = new StoryPassage(@"GymDayOneAva23", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("Ava: I don’t know him too well, but he seems nice at least.");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva24", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #25: GymDayOneAva24

	void passage25_Init()
	{
		this.Passages[@"GymDayOneAva24"] = new StoryPassage(@"GymDayOneAva24", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("Jade: Dante, huh? When can I meet him?");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva25", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #26: GymDayOneAva25

	void passage26_Init()
	{
		this.Passages[@"GymDayOneAva25"] = new StoryPassage(@"GymDayOneAva25", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("Ava: Well, I can try to get in touch with him and set something up by tomorrow. I’ll text you in the morning!");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva26", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #27: GymDayOneAva26

	void passage27_Init()
	{
		this.Passages[@"GymDayOneAva26"] = new StoryPassage(@"GymDayOneAva26", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("Ava: I’m going to get going though. Take care, Jade~");
		yield return lineBreak();
		yield return link("v", "GymDayOneAva27", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #28: GymDayOneAva27

	void passage28_Init()
	{
		this.Passages[@"GymDayOneAva27"] = new StoryPassage(@"GymDayOneAva27", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		Vars.jadeNeutral  = false;
		Vars.jadeHappy  = true;
		yield return text("Jade: See you later, Ava!");
		Vars.avaMeter  = Vars.avaMeter + 10;
		yield return lineBreak();
		yield return link("v", "GymDayOneAvaEnd", null);
		yield break;
	}


	// .............
	// #29: GymDayOneAvaEnd

	void passage29_Init()
	{
		this.Passages[@"GymDayOneAvaEnd"] = new StoryPassage(@"GymDayOneAvaEnd", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}