/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: JadeRoom_DayOne_TextAva.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @JadeRoom_DayOne_TextAva: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Jade", () => this.@Jade, val => this.@Jade = val);
			VarDef("characters", () => this.@characters, val => this.@characters = val);
			VarDef("avaMeter", () => this.@avaMeter, val => this.@avaMeter = val);
			VarDef("centerCharacter", () => this.@centerCharacter, val => this.@centerCharacter = val);
		}

		public StoryVar @Jade;
		public StoryVar @characters;
		public StoryVar @avaMeter;
		public StoryVar @centerCharacter;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@JadeRoom_DayOne_TextAva()
	{
		this.StartPassage = "JadeRoomDayOne-Init";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: JadeRoomDayOne-Init

	void passage1_Init()
	{
		this.Passages[@"JadeRoomDayOne-Init"] = new StoryPassage(@"JadeRoomDayOne-Init", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		Vars.Jade  = "Jade";
		yield return lineBreak();
		yield return lineBreak();
		Vars.characters  = macros1.a(Vars.Jade);
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaMeter  = 20;
		yield return lineBreak();
		yield return lineBreak();
		Vars.centerCharacter  = Vars.Jade;
		yield return lineBreak();
		yield return lineBreak();
		yield return abort(goToPassage: "JadeRoomDayOne01");
		yield break;
	}


	// .............
	// #2: JadeRoomDayOne01

	void passage2_Init()
	{
		this.Passages[@"JadeRoomDayOne01"] = new StoryPassage(@"JadeRoomDayOne01", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Jade: Ah... maybe I should've just gone back to the gym.");
		yield return lineBreak();
		yield return link("v", "JadeRoomDayOne02", null);
		yield break;
	}


	// .............
	// #3: JadeRoomDayOne02

	void passage3_Init()
	{
		this.Passages[@"JadeRoomDayOne02"] = new StoryPassage(@"JadeRoomDayOne02", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Jade: It was a bit rude to just blow her off like that I think.");
		yield return lineBreak();
		yield return link("v", "JadeRoomDayOne03", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #4: JadeRoomDayOne03

	void passage4_Init()
	{
		this.Passages[@"JadeRoomDayOne03"] = new StoryPassage(@"JadeRoomDayOne03", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		using (Group("em", true)) {
			yield return text("Bzzzz Bzzzz");
		}
		yield return lineBreak();
		yield return link("v", "JadeRoomDayOne04", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: JadeRoomDayOne04

	void passage5_Init()
	{
		this.Passages[@"JadeRoomDayOne04"] = new StoryPassage(@"JadeRoomDayOne04", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Jade: Oh-- It's Ava.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva01", null);
		yield break;
	}


	// .............
	// #6: JadeRoomTextAva01

	void passage6_Init()
	{
		this.Passages[@"JadeRoomTextAva01"] = new StoryPassage(@"JadeRoomTextAva01", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Ava: So, I forgot to tell you something pretty important. It’s about AOW stuff.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva02", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: JadeRoomTextAva02

	void passage7_Init()
	{
		this.Passages[@"JadeRoomTextAva02"] = new StoryPassage(@"JadeRoomTextAva02", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Jade: What is it?");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva03", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #8: JadeRoomTextAva03

	void passage8_Init()
	{
		this.Passages[@"JadeRoomTextAva03"] = new StoryPassage(@"JadeRoomTextAva03", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Ava: Well, idk if you guys planned things or anything like that in Cascadia, but AOW is SUPER strict about planning and all that.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva04", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #9: JadeRoomTextAva04

	void passage9_Init()
	{
		this.Passages[@"JadeRoomTextAva04"] = new StoryPassage(@"JadeRoomTextAva04", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return link("<br>Strict about planning?", "JadeRoomTextAva05", null);
		yield return lineBreak();
		yield return link("<br>What are people in AOW planning?", "JadeRoomTextAva05", null);
		yield return lineBreak();
		yield return link("<br>I don't really feel like planning though...", "JadeRoomTextAva05", null);
		yield break;
	}


	// .............
	// #10: JadeRoomTextAva05

	void passage10_Init()
	{
		this.Passages[@"JadeRoomTextAva05"] = new StoryPassage(@"JadeRoomTextAva05", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Ava: AOW requires the talent to plan the match the day before. ");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva06", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11: JadeRoomTextAva06

	void passage11_Init()
	{
		this.Passages[@"JadeRoomTextAva06"] = new StoryPassage(@"JadeRoomTextAva06", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Ava: So look, You have to meet with your opponent on Sundays, the day before the show. During that meeting, you have to plan out what you’ll be doing in the match.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva07", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: JadeRoomTextAva07

	void passage12_Init()
	{
		this.Passages[@"JadeRoomTextAva07"] = new StoryPassage(@"JadeRoomTextAva07", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Ava: The meetings can happen anywhere as long as it’s not too public, you know? Most go for the gym or their own rooms.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva08", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #13: JadeRoomTextAva08

	void passage13_Init()
	{
		this.Passages[@"JadeRoomTextAva08"] = new StoryPassage(@"JadeRoomTextAva08", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Jade: So like… what if I forget something from planning?");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva09", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #14: JadeRoomTextAva09

	void passage14_Init()
	{
		this.Passages[@"JadeRoomTextAva09"] = new StoryPassage(@"JadeRoomTextAva09", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Ava: Well, some people can help you out mid match by calling things, but not too much, y'know?");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva10", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: JadeRoomTextAva10

	void passage15_Init()
	{
		this.Passages[@"JadeRoomTextAva10"] = new StoryPassage(@"JadeRoomTextAva10", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Ava: Others may not take it too well that they have to carry you. So, just try your best to remember, okay?");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva11", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #16: JadeRoomTextAva11

	void passage16_Init()
	{
		this.Passages[@"JadeRoomTextAva11"] = new StoryPassage(@"JadeRoomTextAva11", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Jade: Yeah, got it.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva12", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #17: JadeRoomTextAva12

	void passage17_Init()
	{
		this.Passages[@"JadeRoomTextAva12"] = new StoryPassage(@"JadeRoomTextAva12", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Ava: One more thing! You have your first match with a guy named Dante.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva13", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #18: JadeRoomTextAva13

	void passage18_Init()
	{
		this.Passages[@"JadeRoomTextAva13"] = new StoryPassage(@"JadeRoomTextAva13", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("Ava: He’s known as D-800. Ever heard of him?");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva14", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #19: JadeRoomTextAva14

	void passage19_Init()
	{
		this.Passages[@"JadeRoomTextAva14"] = new StoryPassage(@"JadeRoomTextAva14", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("Jade: I don't think I have.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva15", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #20: JadeRoomTextAva15

	void passage20_Init()
	{
		this.Passages[@"JadeRoomTextAva15"] = new StoryPassage(@"JadeRoomTextAva15", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Ava: Oh right, couldn’t watch D-3. Anyway, I can get a meeting set up for you too. ");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva16", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #21: JadeRoomTextAva16

	void passage21_Init()
	{
		this.Passages[@"JadeRoomTextAva16"] = new StoryPassage(@"JadeRoomTextAva16", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Ava: I’ll text you in the morning about it. (づ｡◕‿‿◕｡)づ Goodnight, Jade!");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #22: JadeRoomTextAva17

	void passage22_Init()
	{
		this.Passages[@"JadeRoomTextAva17"] = new StoryPassage(@"JadeRoomTextAva17", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("Jade: Night, Ava.");
		yield return lineBreak();
		yield return link("v", "JadeRoomTextAva-End", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #23: JadeRoomTextAva-End

	void passage23_Init()
	{
		this.Passages[@"JadeRoomTextAva-End"] = new StoryPassage(@"JadeRoomTextAva-End", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}