/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: JadeRoom_TextAva_Day1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @JadeRoom_TextAva_Day1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Jade", () => this.@Jade, val => this.@Jade = val);
			VarDef("characters", () => this.@characters, val => this.@characters = val);
			VarDef("avaMeter", () => this.@avaMeter, val => this.@avaMeter = val);
			VarDef("centerCharacter", () => this.@centerCharacter, val => this.@centerCharacter = val);
		}

		public StoryVar @Jade;
		public StoryVar @characters;
		public StoryVar @avaMeter;
		public StoryVar @centerCharacter;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@JadeRoom_TextAva_Day1()
	{
		this.StartPassage = "JadeRoomDayOne-Init";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: JadeRoomDayOne-Init

	void passage1_Init()
	{
		this.Passages[@"JadeRoomDayOne-Init"] = new StoryPassage(@"JadeRoomDayOne-Init", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		Vars.Jade  = "Jade";
		yield return lineBreak();
		yield return lineBreak();
		Vars.characters  = macros1.a(Vars.Jade);
		yield return lineBreak();
		yield return lineBreak();
		Vars.avaMeter  = 20;
		yield return lineBreak();
		yield return lineBreak();
		Vars.centerCharacter  = Vars.Jade;
		yield return lineBreak();
		yield return lineBreak();
		yield return abort(goToPassage: "JadeRoom-Day1-1");
		yield break;
	}


	// .............
	// #2: JadeRoom-Day1-1

	void passage2_Init()
	{
		this.Passages[@"JadeRoom-Day1-1"] = new StoryPassage(@"JadeRoom-Day1-1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Jade: Ah... maybe I should've just gone back to the gym.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-Day1-2", null);
		yield break;
	}


	// .............
	// #3: JadeRoom-Day1-2

	void passage3_Init()
	{
		this.Passages[@"JadeRoom-Day1-2"] = new StoryPassage(@"JadeRoom-Day1-2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Jade: It was a bit rude to just blow her off like that I think.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-Day1-3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #4: JadeRoom-Day1-3

	void passage4_Init()
	{
		this.Passages[@"JadeRoom-Day1-3"] = new StoryPassage(@"JadeRoom-Day1-3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		using (Group("em", true)) {
			yield return text("Bzzzz Bzzzz");
		}
		yield return lineBreak();
		yield return link("v", "JadeRoom-Day1-4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: JadeRoom-Day1-4

	void passage5_Init()
	{
		this.Passages[@"JadeRoom-Day1-4"] = new StoryPassage(@"JadeRoom-Day1-4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Jade: Oh-- It's Ava.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-1", null);
		yield break;
	}


	// .............
	// #6: JadeRoom-TextAva-Day1-1

	void passage6_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-1"] = new StoryPassage(@"JadeRoom-TextAva-Day1-1", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Ava: So, I forgot to tell you something pretty important. It’s about AOW stuff.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-2", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: JadeRoom-TextAva-Day1-2

	void passage7_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-2"] = new StoryPassage(@"JadeRoom-TextAva-Day1-2", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Jade: What is it?");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #8: JadeRoom-TextAva-Day1-3

	void passage8_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-3"] = new StoryPassage(@"JadeRoom-TextAva-Day1-3", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Ava: Well, idk if you guys planned things or anything like that in Cascadia, but AOW is SUPER strict about planning and all that.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #9: JadeRoom-TextAva-Day1-4

	void passage9_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-4"] = new StoryPassage(@"JadeRoom-TextAva-Day1-4", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return link("<br>Strict about planning?", "JadeRoom-TextAva-Day1-5", null);
		yield return lineBreak();
		yield return link("<br>What are people in AOW planning?", "JadeRoom-TextAva-Day1-5", null);
		yield return lineBreak();
		yield return link("<br>I don't really feel like planning though...", "JadeRoom-TextAva-Day1-5", null);
		yield break;
	}


	// .............
	// #10: JadeRoom-TextAva-Day1-5

	void passage10_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-5"] = new StoryPassage(@"JadeRoom-TextAva-Day1-5", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Ava: AOW requires the talent to plan the match the day before. ");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-6", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11: JadeRoom-TextAva-Day1-6

	void passage11_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-6"] = new StoryPassage(@"JadeRoom-TextAva-Day1-6", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Ava: So look, You have to meet with your opponent on Sundays, the day before the show. During that meeting, you have to plan out what you’ll be doing in the match.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-7", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: JadeRoom-TextAva-Day1-7

	void passage12_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-7"] = new StoryPassage(@"JadeRoom-TextAva-Day1-7", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Ava: The meetings can happen anywhere as long as it’s not too public, you know? Most go for the gym or their own rooms.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-8", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #13: JadeRoom-TextAva-Day1-8

	void passage13_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-8"] = new StoryPassage(@"JadeRoom-TextAva-Day1-8", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Jade: So like… what if I forget something from planning?");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-9", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #14: JadeRoom-TextAva-Day1-9

	void passage14_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-9"] = new StoryPassage(@"JadeRoom-TextAva-Day1-9", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Ava: Well, some people can help you out mid match by calling things, but not too much, y'know?");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-10", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: JadeRoom-TextAva-Day1-10

	void passage15_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-10"] = new StoryPassage(@"JadeRoom-TextAva-Day1-10", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Ava: Others may not take it too well that they have to carry you. So, just try your best to remember, okay?");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-11", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #16: JadeRoom-TextAva-Day1-11

	void passage16_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-11"] = new StoryPassage(@"JadeRoom-TextAva-Day1-11", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Jade: Yeah, got it.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-12", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #17: JadeRoom-TextAva-Day1-12

	void passage17_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-12"] = new StoryPassage(@"JadeRoom-TextAva-Day1-12", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Ava: One more thing! You have your first match with a guy named Dante.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-13", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #18: JadeRoom-TextAva-Day1-13

	void passage18_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-13"] = new StoryPassage(@"JadeRoom-TextAva-Day1-13", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("Ava: He’s known as D-800. Ever heard of him?");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-14", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #19: JadeRoom-TextAva-Day1-14

	void passage19_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-14"] = new StoryPassage(@"JadeRoom-TextAva-Day1-14", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("Jade: I don't think I have.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-15", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #20: JadeRoom-TextAva-Day1-15

	void passage20_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-15"] = new StoryPassage(@"JadeRoom-TextAva-Day1-15", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Ava: Oh right, couldn’t watch D-3. Anyway, I can get a meeting set up for you too. ");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-16", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #21: JadeRoom-TextAva-Day1-16

	void passage21_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-16"] = new StoryPassage(@"JadeRoom-TextAva-Day1-16", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Ava: I’ll text you in the morning about it. (づ｡◕‿‿◕｡)づ Goodnight, Jade!");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-17", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #22: JadeRoom-TextAva-Day1-17

	void passage22_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-17"] = new StoryPassage(@"JadeRoom-TextAva-Day1-17", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("Jade: Night, Ava.");
		yield return lineBreak();
		yield return link("v", "JadeRoom-TextAva-Day1-End", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #23: JadeRoom-TextAva-Day1-End

	void passage23_Init()
	{
		this.Passages[@"JadeRoom-TextAva-Day1-End"] = new StoryPassage(@"JadeRoom-TextAva-Day1-End", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}